### PR TITLE
frint-router-component-handlers

### PR DESCRIPTION
**Pull request by viacheslaff**
This PR introduces `frint-router-component-handlers` package, an abstraction layer for frint-router-* view libraries and contains business logic that can be reused. It's done in similar way to #277.
 `frint-router-react` was updated to use it.

### CODE REVIEW

**Comment by fahad19** [comment]
Cool stuff, @viacheslaff! 💖 

Can approve after successful Travis-CI build.

**Comment by fahad19** [comment]
Is the `router` example tested manually with these new changes?

**Comment by viacheslaff** [comment]
@fahad19, yes `router` example works in the branch. Although it doesn't use the `frint-router-react` which uses `frint-router-component-handlers`, because the latter isn't published yet.
I wonder how we go about - publish new package to npm or merge to master first with example relying on previous versions? It's a chicken-egg problem

**Comment by fahad19** [comment]
`npm link` may help in testing locally: https://docs.npmjs.com/cli/link

**Comment by viacheslaff** [comment]
`router` example tested and is working

**Comment by fahad19** [comment]
can you please add the new package in:

* `docsSidebar.html`
* `README.md` in the root

**Comment by viacheslaff** [comment]
@fahad19, added the package to the docs

**Comment by fahad19** [comment]
💖

**Pull request merged**
