### PR TITLE
Feature #193, allow loading root and child apps asynchronously

### PR DESCRIPTION
**Pull request by reaktivo**
Not actually a feature, but updated the Multiple Apps example to show how a developer might implement asynchronous loading and execution of apps. This allows the browser to download multiple apps in parallel and for the possibility of the root app to load after any child app.

### CODE REVIEW

**Comment by fahad19** [comment]
Refs #193

**Comment by fahad19** [comment]
This is really cool, @reaktivo! 💖

**Comment by reaktivo** [comment]
@alexmiranda @fahad19 What do you guys think about not exposing the root app global when in production environments?

**Comment by fahad19** [comment]
@reaktivo: can you please explain further? I am curious how we can register other Apps being loaded from separate bundles.

**Comment by reaktivo** [comment]
@fahad19 The idea was this: https://gist.github.com/reaktivo/7709df18e800ca35f4bcedaaaa4aec66 but then I thought it doesn't make any sense, any developer with access to a debugger could access the root app instance if they wanted to anyway.

**Comment by fahad19** [comment]
@reaktivo: 👍 

btw, are you planning to write a new page in this PR under the `How TOs` section here for async loading? https://frint.js.org/guides/

**Comment by reaktivo** [comment]
@fahad19 Yes, it's coming.

**Comment by fahad19** [comment]
@reaktivo: we are planning to release a new 1.x version, before we gear up for 2.x with latest React.

any chance this PR can be merged soon so it goes into 1.x?

**Comment by reaktivo** [comment]
@fahad19 @alexmiranda Any comments on this PR?

**Comment by fahad19** [comment]
@reaktivo: lgtm 👍

**Comment by alexmiranda** [comment]
LGTM. :+1:

**Pull request merged**
