### PR TITLE
Memory Leak

### PR DESCRIPTION
**Pull request by jackTheRipper**
** Do **

Fix a memory leak in the App.

### CODE REVIEW

**Comment by fahad19** [comment]
Could you kindly rebase your commits from latest `next`? The diff (commits list) should only show your commits :)

Very well done with RxJS usage! 💖

**Comment by jackTheRipper** [comment]
@fahad19 : rebased !

**Comment by fahad19** [comment]
The first two commits still need to go away:

* `examples: kitchensink`
* `register widgets`

As seen here: https://github.com/Travix-International/frint/pull/90/commits

---

screen shot 2017-03-01 at 09 57 09

**Comment by jackTheRipper** [comment]
I am closing this PR the rebase is messy.

New one here: https://github.com/Travix-International/frint/pull/93

**Pull request closed without merging**
